name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Briefly describe the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Tap on '...'
        3. Scroll to '...'
        4. Error occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe how it should work
    validations:
      required: true

  - type: checkboxes
    id: platform
    attributes:
      label: Platform
      description: Select the platform(s) where the bug occurs
      options:
        - label: iOS
        - label: Android
        - label: Web
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Device name, OS version, Expo SDK version, etc.
      placeholder: |
        - Device: iPhone 16 Pro
        - OS: iOS 18.2
        - Expo SDK: 54
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Screenshots / Logs
      description: Attach screenshots or error logs if available
    validations:
      required: false
