name: Feature Request
description: 新しい機能を提案する
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
      description: どのような課題や不便を解決したいですか？
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: どのような機能や改善を提案しますか？
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 検討した代替案
      description: 他に検討した解決策があれば記載してください
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 補足情報
      description: 参考リンク、スクリーンショットなど追加情報があれば記載してください
    validations:
      required: false
